### ISSUE TITLE
[0.5pt] Create Item class with methods - Group task

### ISSUE THREAD

**Issue by mikemtzp** [mikemtzp/Catalog-of-my-things#1]
- Create Item class in a separate .rb file.
- All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.

- Implement methods:
  - can_be_archived?() in the Item class
    - should return true if published_date is older than 10 years
    - otherwise, it should return false
  - move_to_archive() in the Item class
    - should reuse can_be_archived?() method
    - should change the archived property to true if the result of the can_be_archived?() method is true
    - should do nothing if the result of the can_be_archived?() method is false

- Add all methods visible in the diagram.

![image](https://user-images.githubusercontent.com/97407840/188487499-7c5f61a2-1a7c-47ff-9e7f-e2cde66678b9.png)

**Comment by Daf98** [comment]
https://github.com/mikemtzp/Catalog-of-my-things/pull/22
