### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by mikemtzp** [mikemtzp/Catalog-of-my-things#21]
There are 3 people in our team with the following roles:

- Team member 1 - @mikemtzp
- Team member 2 - @Daf98 
- Team member 3 - @Draxeytina 

[See GitHub project here](https://github.com/mikemtzp/Catalog-of-my-things/projects/1)

**Comment by Lordkaito** [comment]
Hi @mikemtzp, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikemtzp** [comment]
_**UDPATE: A new team member was added to our team.**_

- Team member 4 - @KaskMIL
